using EmailScheduler.DAL;
using EmailScheduler.DTO;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Text;

namespace EmailScheduler_Library
{
    public class EmailGenerator
    {
        IEmailAddressRepo repo = new EmailAddressRepo();        
        Email email = new Email();        
        public void StartEmailDelivery()
        {
            List<EmailAddresses> mailList = repo.GetEmailAddresses();
            email.From = ConfigurationManager.AppSettings["From"];
            email.Password = ConfigurationManager.AppSettings["Password"];
            foreach (var mailadd in mailList)
            {
                email.To = mailadd.EmailAddress;
            }
            EmailSender.DispatchMail(email);
        }

        public string GetEmailBody(string User)
        {
            return "<div>Dear ," + User+
                "<br>" +
                "<br>" +"Please click on below link"    +            "<br>" +
            
                "<br>" +
                "<br>" +
                "Thanks & Regards," +
                "<br>" +
                "Team CusJo" +
                "<br>" +
                "<br>" +
                "This Email is auto generated by the System." +
                "</div>";
        }


    }
}
